# Generated by Django 4.2.4 on 2023-11-11 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("short_description", models.TextField(max_length=280)),
                ("reward", models.CharField(blank=True, max_length=280, null=True)),
                ("long_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Hexagon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Inactive"),
                            (1, "Strength"),
                            (2, "Agility"),
                            (3, "Aerobic"),
                            (4, "Flexibility"),
                        ],
                        default=0,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TileMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=2023, unique=True)),
                (
                    "hexagons",
                    models.ManyToManyField(
                        blank=True,
                        max_length=1024,
                        related_name="tilemap_hexagons",
                        to="challenges.hexagon",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="segment",
            constraint=models.UniqueConstraint(
                fields=("type", "position"), name="unique_segment"
            ),
        ),
        migrations.AddConstraint(
            model_name="segment",
            constraint=models.CheckConstraint(
                check=models.Q(("position__gte", 1), ("position__lte", 6)),
                name="position_range",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="challenges.challenge",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="hexagon",
            name="segments",
            field=models.ManyToManyField(
                blank=True, related_name="hexagon_segments", to="challenges.segment"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="challenge",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="challenges.challenge",
            ),
            preserve_default=False,
        ),
    ]
