# Generated by Django 4.2.4 on 2023-11-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_challenge_hexagon_participant_segment_tilemap_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hexagon",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="hexagon",
            name="unique_hexagon",
        ),
    ]
