# Generated by Django 4.2.4 on 2023-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_challenge_hexagon_participant_segment_tilemap_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="segment",
            name="position_range",
        ),
        migrations.AddField(
            model_name="hexagon",
            name="position",
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
        migrations.AddConstraint(
            model_name="hexagon",
            constraint=models.CheckConstraint(
                check=models.Q(("position__gte", 1), ("position__lte", 1024)),
                name="hexagon_position_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="segment",
            constraint=models.CheckConstraint(
                check=models.Q(("position__gte", 1), ("position__lte", 6)),
                name="segment_position_range",
            ),
        ),
    ]
