# Generated by Django 4.2.4 on 2023-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_friendrequest_delete_profile_user_friends_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
